#!/bin/bash

if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    ls
    cd  lib
    ls
    echo "Compile CGNS Source"
    tar xzvf CGNS-3.4.0.tar.gz
    ls
    cd CGNS-3.4.0
    ls
    echo "compiler is $C_COMPILER"
    mkdir build
    cd build
    ls
    #cmake -G "Unix Makefiles" -SCGNS-3.4.0 -BCGNS-3.4.0/build -DCGNS_ENABLE_64BIT="ON" -DCGNS_BUILD_SHARED="OFF" -DCMAKE_INSTALL_PREFIX=cgns
    cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr/local/cgns ../
    make -j 8
    sudo make install
    ls /usr/local
fi
