#!/bin/bash

if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    ls
    cd  lib
    ls
    echo "Compile CGNS Source"
    tar xzvf CGNS-3.4.0.tar.gz
    ls
    cd CGNS-3.4.0
    ls
    echo "C_COMPILER is $C_COMPILER"
    echo "CXX_COMPILER is $CXX_COMPILER"
    mkdir build
    cd build
    pwd
    ls
    echo "TRAVIS_BUILD_DIR is $TRAVIS_BUILD_DIR"
    echo "source is $TRAVIS_BUILD_DIR/lib/CGNS-3.4.0"
    echo "build is $TRAVIS_BUILD_DIR/lib/CGNS-3.4.0/build"
    #cmake -G "Unix Makefiles" -SCGNS-3.4.0 -BCGNS-3.4.0/build -DCGNS_ENABLE_64BIT="ON" -DCGNS_BUILD_SHARED="OFF" -DCMAKE_INSTALL_PREFIX=cgns
    #cmake -G "Unix Makefiles" -DCMAKE_INSTALL_PREFIX=/usr/local/cgns ../
    #cmake -G "Unix Makefiles" -DCGNS_ENABLE_64BIT="ON" -DCMAKE_INSTALL_PREFIX=/usr/local/cgns ../
    cmake --help
    cmake -G "Unix Makefiles" $TRAVIS_BUILD_DIR/lib/CGNS-3.4.0 $TRAVIS_BUILD_DIR/lib/CGNS-3.4.0/build/  \
          -DCMAKE_C_COMPILER=$C_COMPILER -DCMAKE_CXX_COMPILER=$CXX_COMPILER -DCGNS_ENABLE_64BIT="ON" \
          -DCGNS_BUILD_SHARED="OFF" -DCMAKE_INSTALL_PREFIX=/usr/local/cgns 
    echo "----------------------------------------"
    cmake -G "Unix Makefiles" /home/travis/build/eric2003/OneFLOW/lib/CGNS-3.4.0/  /home/travis/build/eric2003/OneFLOW/lib/CGNS-3.4.0/build
    make -j 8
    sudo make install
    ls /usr/local
fi
