#!/bin/bash

if [ "$TRAVIS_OS_NAME" == "linux" ]; then
    ls
    cd  lib
    ls
    echo "Compile METIS Source"
    tar xzvf metis-5.1.0eric.tar.gz
    cd metis-5.1.0eric
    ls
    echo "compiler is $C_COMPILER"
    make config cc=$C_COMPILER
    make
    ls
    sudo make install 
    ls /usr/local
fi
