function ( GetAllSubDir result currdir )
    file ( GLOB children RELATIVE ${currdir} ${currdir}/* )
    set ( dirlist "")
    foreach ( child ${children} )
        message ( STATUS "The child is ${child}" )
        if ( IS_DIRECTORY ${currdir}/${child} )
            list ( APPEND dirlist ${child} )
        endif()
    endforeach()
    set ( ${result} ${dirlist} PARENT_SCOPE )
endfunction()

function ( SetSourceGroup my_head_list my_src_list my_include_dirs )
    set ( tmp_header_list "" )
	set ( tmp_src_list "" )
	set ( tmp_include_dirs "" )
    foreach( dir ${dirList} )
        message ( STATUS " The dir is ${dir} " )
        file ( GLOB header_files "${dir}/include/*.h" )
        file ( GLOB src_files "${dir}/src/*.cpp" )
        file ( GLOB hpp_files "${dir}/src/*.hpp" )
		set( include_dir "${CMAKE_CURRENT_SOURCE_DIR}/${dir}/include" )
		list ( APPEND tmp_include_dirs ${include_dir} )
        #include_directories( "${CMAKE_CURRENT_SOURCE_DIR}/${dir}/include" )
		
        if ( NOT( hpp_files STREQUAL "" ) )
            #include_directories( "${CMAKE_CURRENT_SOURCE_DIR}/${dir}/src" )		
		    set( hpp_file_include_dir "${CMAKE_CURRENT_SOURCE_DIR}/${dir}/src" )
			list ( APPEND tmp_include_dirs ${hpp_file_include_dir} )
        endif()

        message( STATUS "The header_files is ${header_files}" )
        message( STATUS "The srcFile is ${src_files}" )
    
        source_group ( "${dir}\\include" FILES ${header_files} )
        source_group ( "${dir}\\src" FILES ${src_files} )
        list ( APPEND tmp_header_list ${header_files} )
        list ( APPEND tmp_src_list  ${src_files} )
    endforeach()
	message ( STATUS " tmp_include_dirs = ${tmp_include_dirs} " )
    set ( ${my_head_list} ${tmp_header_list} PARENT_SCOPE )
    set ( ${my_src_list} ${tmp_src_list} PARENT_SCOPE )
	set ( ${my_include_dirs} ${tmp_include_dirs} PARENT_SCOPE )
endfunction()

function ( fun_include_directories )
    set ( my_include_dirs ${ARGV} )
    message ( STATUS " in fun_include_directories " )
	message ( STATUS " my_include_dirs = ${my_include_dirs} " )
    foreach( dir ${my_include_dirs} )
        message ( STATUS " The dir in fun_include_directories is ${dir} " )
        include_directories( ${dir} )
    endforeach()
endfunction()
